/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/CodeViewer': RouteRecordInfo<'/CodeViewer', '/CodeViewer', Record<never, never>, Record<never, never>>,
    '/FileMenu': RouteRecordInfo<'/FileMenu', '/FileMenu', Record<never, never>, Record<never, never>>,
    '/Form': RouteRecordInfo<'/Form', '/Form', Record<never, never>, Record<never, never>>,
    '/FramesList': RouteRecordInfo<'/FramesList', '/FramesList', Record<never, never>, Record<never, never>>,
    '/LayersTree': RouteRecordInfo<'/LayersTree', '/LayersTree', Record<never, never>, Record<never, never>>,
    '/NumberField': RouteRecordInfo<'/NumberField', '/NumberField', Record<never, never>, Record<never, never>>,
    '/SelectField': RouteRecordInfo<'/SelectField', '/SelectField', Record<never, never>, Record<never, never>>,
    '/ToolBar': RouteRecordInfo<'/ToolBar', '/ToolBar', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/components/CodeViewer.story.vue': {
      routes: '/CodeViewer'
      views: never
    }
    'src/components/FileMenu.story.vue': {
      routes: '/FileMenu'
      views: never
    }
    'src/components/Form.story.vue': {
      routes: '/Form'
      views: never
    }
    'src/components/FramesList.story.vue': {
      routes: '/FramesList'
      views: never
    }
    'src/components/LayersTree.story.vue': {
      routes: '/LayersTree'
      views: never
    }
    'src/components/NumberField.story.vue': {
      routes: '/NumberField'
      views: never
    }
    'src/components/SelectField.story.vue': {
      routes: '/SelectField'
      views: never
    }
    'src/components/ToolBar.story.vue': {
      routes: '/ToolBar'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
